logging:
  level:
    root: info
server:
  port: 9091
spring:
  application:
    name: service-hi-v1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
    register-with-eureka: true
